language: go

go:
  - 1.13.x
  - 1.14.x
env:
  - GO111MODULE=on

services:
  - mysql
  - redis-server

before_install:
  - mysql -e 'CREATE DATABASE temp_db DEFAULT CHARACTER SET utf8;'

#script: go test -v

script:
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)