# debug模式
debug = true
# 是否开启jwt
jwt_flag = false
# 关闭swag的标志
swagger_flag = "iris_swag"
# todo 还需要再确认
iris_logger_level = "debug"

[database]
host = "127.0.0.1"
port = 3306
user = "root"
password = ""
db_name = "temp_db"

[redis]
addr = "127.0.0.1:6379"
password = ""
db = 0

[web]
port = 18080
page_size = 10

[secret]
jwt = "1234567890123456"

[log]
info_file = "./log"
error_file = "./log"
